#!/usr/bin/python3
import pygame;
import time;

surface = pygame.display.set_mode([340,200]);
pygame.display.flip();
def draw(c1,c2,c3,sx,sy,x,y):
    pygame.draw.rect(surface, (c1,c2,c3), (sx,sy,x,y));
surface.fill((255,255,255));
draw(255,0,0, 0,0, 340,67);
draw(255,255,255, 0,67, 340,67);
draw(0,0,0, 0,134, 340,67);
pygame.display.update();
while True:
    pass;
